
### Register
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "zura",
  "email": "zura@example.com",
  "password": "2222"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "zura",
  "password": "2222"
}