
### Register
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "zura",
  "email": "zura@example.com",
  "password": "2222"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "zura",
  "password": "2222"
}


### Create Subreddit
POST http://localhost:8080/subreddit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ6dXJhIiwiZXhwIjoxNTk2NzQ1MzA1fQ.E5d3pXCSQb7YkpOIFhuyfIznyR_tNENFf0_SAaPsVEs

{
  "name": "php"
}